#!/bin/bash

CPU_LOAD=$(cat /proc/loadavg | awk '{print $2}')  #cpu load over the last 5 minutes

if [ -n "$THRESHOLD" ]; then
    if [ $(echo "$CPU_LOAD > $THRESHOLD" | bc -l) == "1" ]; then
        I3B_COLOR="$I3B_COLOR_BAD"
        notify-send -u critical "ACHTUNG!" "CPU is overloaded!"
    fi
fi

echo "$CPU_LOAD"    #full_text
echo "$CPU_LOAD"    #short_text
echo "$I3B_COLOR"   #color
