#!/bin/bash

CPU_TEMP=$(cat /sys/class/thermal/thermal_zone0/temp | awk '{print $1/1000}')

if [ $CPU_TEMP -ge $THRESHOLD ]; then
    I3B_COLOR="$I3B_COLOR_BAD"
    notify-send -u critical "ACHTUNG!" "CPU is overheating!"
fi

echo "$CPU_TEMP°C" #full_text
echo "$CPU_TEMP°C" #short_text
echo "$I3B_COLOR"  #color
