#!/bin/bash

AWK_CODE='BEGIN {
    FS="=";
    status="";
    capacity=0;
}
{
    if ($0 ~ /STATUS/) {
        status=$2;
    }
    else if ($0 ~ /CAPACITY=/ ) {
        capacity=$2;
    }
}
END {
    print status " " capacity;
}
'

if ! [ -d "${INSTANCE}" ]; then
    echo "No battery"
    exit 1 
fi

RESULT=$(cat "${INSTANCE}/uevent" | awk "$AWK_CODE")
STATUS=$(echo "${RESULT}" | awk '{print $1}')
CAPACITY=$(echo "${RESULT}" | awk '{print $2}')

if [ "${STATUS}" = "Discharging" ]; then
    if [ ${CAPACITY} -le ${LOW_THR} ]; then
        notify-send --urgency=critical "ACHTUNG!" "Battery level is critically low!"
        xmbr_colorify "${CAPACITY}%" "${LOW_CLR}"
    fi
fi

xmbr_colorify "${CAPACITY}%" "${NORMAL_CLR}" 
